### ISSUE TITLE
This is a great idea.

### ISSUE THREAD

**Issue by daviewales** [abhinavsharma/hypersearch#1]
I'm keen to see where this goes!
I tried to [hack something like this together](https://gitlab.com/daviewales/the-alternet) by using whitelists in [uBlacklist](https://iorate.github.io/ublacklist/docs).
But it didn't work because uBlocklist just filters the results on the search page after the page has been sent to your browser, which generally resulted in a completely empty browser page.

Keen for the Firefox extension!

**Comment by abhinavsharma** [comment]
Thank you! The Firefox version is now live https://addons.mozilla.org/en-US/firefox/addon/hypersearch-desktop/
