### ISSUE TITLE
Experiencing login problems when Hypersearch is enabled

### ISSUE THREAD

**Issue by LECAGO** [abhinavsharma/hypersearch#2]
**Describe the bug**
I know this is gonna sound strange, but my logins to certain websites will bug out when I enable the Hypersearch extension. I noticed this on certain websites. On reddit.com I appear logged out on first load, then logged in on refresh. My session also does not carry over to new tabs. On lichess.org and osu.ppy.sh they straight up refuse login and forgot password entries.

**To Reproduce**
1. Attempt login on any of above websites with Hypersearch extension enabled
2. Cannot login. osu.ppy.sh specifically throws a 403 forbidden.

**Expected behavior**
I should log in without any issue.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19044 Build 19044
 - Firefox 99.0.1 (64-bit)

**Comment by felipewil** [comment]
Hi @LECAGO, thanks for the report. We have prepared a fix and it will be in the next release.

**Comment by felipewil** [comment]
@LECAGO, version 0.0.109 is released. I'll close this issue but let us know if there is any other in the future. Thanks.
