### ISSUE TITLE
Lens icons show up broken on Firefox 100.0 64bit on Manjaro Linux

### ISSUE THREAD

**Issue by Asmageddon** [abhinavsharma/hypersearch#4]
It's not an interaction with another addon, as disabling all others does not resolve it.
This is what it looks like, as you can see the sidebar is unusable:

![image](https://user-images.githubusercontent.com/300991/170330159-e52b180c-434b-4414-98a0-bbb7b808f869.png)

**Comment by felipewil** [comment]
@Asmageddon, could you share the browser you are using and the extension version?

**Comment by Asmageddon** [comment]
@felipewil Version 0.0.106

**Comment by felipewil** [comment]
@Asmageddon, thanks. Do you mind getting the latest version and telling us if the problem persists?

https://addons.mozilla.org/en-US/firefox/addon/hyperweb-desktop/ (btw, it was rebranded as Hyperweb)

**Comment by Asmageddon** [comment]
Ah, I see. Was the rebranding why it failed to update?

It seems to work fine now, though I must say - this is one bulky, slow extension on an ancient Core2Duo ;(

**Comment by felipewil** [comment]
@Asmageddon glad to hear it's working now and sorry that's slow on an older cpu. We'll keep an eye for possible performance improvements.

**Comment by felipewil** [comment]
Closing.
